config/routes.rb
Rails.application.routes.draw do
  get 'purchase/index'
  get 'purchase/done'
  get 'card/new'
  get 'card/show'
  devise_for :users
  root 'test#index'
  resources :search,only: [:index]
  resources :category,only:[:index,:show,:new]
  resource :mypage do
    resource :profile ,only: [:show]
    resource :cards ,only: [:new, :show, :create] do
      collection do
        post 'pay', to: 'cards#pay'
        post 'delete', to: 'cards#delete'
        get 'credit_add', to: 'cards#credit_add'
      end
    end
    resource :logout ,only: [:show]
    resource :listings ,only:[:show] do
      resources :display, only:[:show,:destroy]
    end
  end
  resources :items, only: [:show,:destroy]


  resources :sells,only:[:index,:new,:create,:edit,:update]

  resource :users,only: [:new]
  
  resources :signup do
    collection do
      get 'new_login'
      get 'login_menber_information'
      get 'login_phone_number'
      get 'new_login_adress' # ここで、入力の全てが終了する
      get 'new_login_complete' # 登録完了後のページ
    end
  end

  resources :purchase, only: [:index, :show] do
    collection do
      # get 'show', to: 'purchase#show'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end
end

app/views/shared/_card.haml
.pickup-category-items-box
  %h3.pickup-category-items-box__genre-newitems
    レディース新着アイテム
  .item-box-contents
    = render "shared/toppage-itembox"
  .item-box-contents__view-all
    すべての商品を見る

app/views/shared/_credit_confirmation.haml
= form_with url: delete_mypage_cards_path, method: :post, local: true, id: 'charge-form' do |f|
  .credit-card-comfirmation
    .credit-card-comfirmation__title
      支払い方法
    .credit-card-comfirmation__box
      .credit-card-comfirmation__box__top
        .your-card
          .your-card__index
            クレジットカード一覧
          .your-card__info
            .your-card__info__icon
              =image_tag "jcb.png", size: "25x25"
              = f.submit "削除する", {class: "your-card__info__remove"}
            .your-card__info__number
              = "**** **** **** " + @default_card_information.last4
            .your-card__info__limit
              - exp_month = @default_card_information.exp_month.to_s
              - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
              = exp_month + " / " + exp_year
      .credit-card-comfirmation__box__bottom
        =link_to "支払い方法について ＞","",class: "credit-card-comfirmation__box__link"

app/views/shared/_credit_info.haml
= form_with url: pay_mypage_cards_path, method: :post, html: {name: "inputForm"} do |f|
  .credit-card-resistration
    .credit-card-resistration__title
      クレジットカード情報入力
    .credit-card-resistration__box
      .card-information-box
        .card-information-box__card-number
          .label-require-icon
            %label.card-information-box__label カード番号
            .hissu_tag
              必須
          = f.text_field :number, class: "card-information-box__input", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
          = image_tag("creditcards.png", class:"card-information-box__picture")
        .card-information-box__expiration
          .label-require-icon
            %label.card-information-box__label 有効期限
            .hissu_tag
              必須
          = f.select :exp_month, [["--",""],["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{} , class: 'card-information-box__select '
          %span.card-information-box__select__text 月
          = f.select :exp_year, [["--",""],["19",2019],["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]],{} , class: 'card-information-box__select'
          %span.card-information-box__select__text 年
        .card-information-box__security
          .label-require-icon
            %label.card-information-box__label セキュリティコード
            .hissu_tag
              必須
          = f.text_field :cvc, class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc",class: "card-information-box__input"
          #card_token
          = f.submit "追加する", id: "token_submit", class: "card-information-box__submit"

app/views/shared/_footer-log.haml
.log-body__footer
  %ul.log-body__footer__clearfix
    %li.log-body__footer__clearfix__privacy プライバシーポリシー
    %li.log-body__footer__clearfix__tos  メルカリ利用規約
    %li.log-body__footer__clearfix__tokutei  特定商取引に関する表記
  .log-body__footer__logo
    = image_tag "image_grey.png" , width: 100 , height: 65
  .log-body__footer__small
    ©️2019 Mercari

app/views/shared/_header.haml
.toppage-header
  .toppage-header__box
    .toppage-header__box__top
      %h1.mercari-top-logo
        = link_to root_path do
          = image_tag 'main-logo.png', height: '52', width: '167'
      .toppage-header__box__top__right
        = form_with url: search_index_path, class:'buy-form',method: :get, local: true do|f|
          .toppage-header__box__top__right__search
            - if @keywords == nil
              = f.text_field :search,class: "search", placeholder: "何かお探しですか？"
            - else
              = f.text_field :search,class: "search", value: "#{@keywords}"
          %label
            .toppage-header__box__top__right__icon
              = f.submit 
              = fa_icon 'search', class: "search-icon"
    .toppage-header__box__bottom
      .toppage-header__box__bottom__li
        %ul.toppage-header__box__bottom__li__left
          %li.toppage-header__box__bottom__li__left__li-search.append-categories
            = fa_icon 'list-ul', class: "search-icon-left append-categories"
            = link_to category_index_path, class: "search-brand-category append-categories" do
              カテゴリーから探す
          %li.toppage-header__box__bottom__li__left__li-search
            = fa_icon 'tag', class: "search-icon-left"
            = link_to "", class: "search-brand-category append-ctegories" do
              ブランドから探す
      .category-delete-area
      .category-delete-are-side
      .category_list.item-categories
        .parents_list.hidden-categories
          - @parents.each do |parent|
            = link_to "#{parent.name}", category_path(parent), class: "parent_category",id: "#{parent.id}"
        .children_list
        .grand_children_list

      - if user_signed_in?
        %ul.toppage-header__box__bottom__li__right
          %li.toppage-header__box__bottom__li__right__iine
            = link_to "", class: "iine-message-todo" do
              = fa_icon 'heart', class: "search-icon-right"
              %span
                いいね！一覧
          %li.toppage-header__box__bottom__li__right__message
            = link_to "", class: "iine-message-todo" do
              = fa_icon 'bell', class: "search-icon-right"
              お知らせ
          %li.toppage-header__box__bottom__li__right__todo
            = link_to "", class: "iine-message-todo" do
              = fa_icon 'check', class: "search-icon-right"
              やることリスト
          %li.toppage-header__box__bottom__li__right__mypage
            = image_tag 'avator.png', class: 'gotomypage-icon', height: '32', width: '32'
            = link_to mypage_path, class: "gotomypage" do
              マイページ
      - else
        %ul.toppage-header__box__bottom__li__right2
          %li.toppage-header__box__bottom__li__right2__signup
            = link_to new_login_signup_index_path, class: "toppage-header__box__bottom__li__right2__signup__icon" do
              新規会員登録
          %li.toppage-header__box__bottom__li__right2__login
            = link_to new_user_session_path, class: "toppage-header__box__bottom__li__right2__login__icon" do
              ログイン

app/views/shared/_items.haml
%h1.heading 
  = @item.name
.main-container-hatapon
  .main-container-hatapon--left
    .main-container-hatapon--left--big
      = image_tag "#{ @item.images.first.url}", class: "photo-screen"
    .main-container-hatapon--left--small
      - @item.images.each do |image|
        .main-container-hatapon--left--small__1
          = image_tag "#{image.url}", class: "photo-screen"
        
  %table.main-container-hatapon--right
    %tr.main-container-hatapon--right--wide
      %th.main-container-hatapon--right--wide__question 出品者
      %td.main-container-hatapon--right--wide__value
        //user のp路フィールに飛ばす
        = link_to  "", class: "table-a sender-name" do
          %p 
            = @item.user.nickname
        .main-container-hatapon--right--wide__value__face-number
          = fa_icon "smile-o", class: "main-container--right--wide__value__face-number--good"
          %span.main-container-hatapon--right--wide__value__face-number__number 12
        .main-container-hatapon--right--wide__value__face-number
          = fa_icon "meh-o", class: "main-container--right--wide__value__face-number--normal"
          %span.main-container-hatapon--right--wide__value__face-number__number 12
        .main-container-hatapon--right--wide__value__face-number
          = fa_icon "frown-o", class: "main-container--right--wide__value__face-number--bad"
          %span.main-container-hatapon--right--wide__value__face-number__number 120             
    %tr.main-container-hatapon--right--wide
      %th.main-container-hatapon--right--wide__question カテゴリー
      %td.main-container-hatapon--right--wide__value
        = link_to category_path(@item.category.parent.parent.id) , class:"table-a classification" do
          =@item.category.parent.parent.name
        = link_to category_path(@item.category.parent.id), class: "table-a classification" do
          = fa_icon "arrow-right"
          %span 
            = @item.category.parent.name
        = link_to category_path(@item.category.id), class: "table-a classification" do
          = fa_icon "arrow-right"
          %span 
            = @item.category.name
    %tr.main-container-hatapon--right--wide
      %th.main-container-hatapon--right--wide__question ブランド
      %td.main-container-hatapon--right--wide__value
        = link_to "NASA", "", class: "table-a"
    - if @item.size.present?
      %tr.main-container-hatapon--right--wide
        %th.main-container-hatapon--right--wide__question 商品のサイズ
        %td.main-container-hatapon--right--wide__value 
          = @item.size
    %tr.main-container-hatapon--right--wide
      %th.main-container-hatapon--right--wide__question 商品の状態
      %td.main-container-hatapon--right--wide__value 
        = Condition.find(@item.condition).name
    %tr.main-container-hatapon--right--wide
      %th.main-container-hatapon--right--wide__question 配送料の負担
      %td.main-container-hatapon--right--wide__value 
        -begin
          = Cost.find(@item.send_cost).name
        -rescue
          = "----"
    %tr.main-container-hatapon--right--wide
      %th.main-container-hatapon--right--wide__question 配送の方法
      %td.main-container-hatapon--right--wide__value 
        = Post.find(@item.send_method).name
    %tr.main-container-hatapon--right--wide
      %th.main-container-hatapon--right--wide__question 配送元地域
      %td.main-container-hatapon--right--wide__value 
        = Prefecture.find(@item.send_place).name
    %tr.main-container-hatapon--right--wide
      %th.main-container-hatapon--right--wide__question 発送日の目安
      %td.main-container-hatapon--right--wide__value 
        = Day.find(@item.send_day).name
.price-box
  %span.price-box__number 
    - price = add_comma(@item.price)
    = "¥#{price}" 
  %span.price-box__tax (税込)
  %span.price-box__send-tax 送料込み
= link_to "購入画面に進む", purchase_path(@item.id), class: "red-button"
%p.item-description 
  = @item.content

app/views/shared/_logout.haml
.log-out-box
  -# =form_with model: @user,url: user_registration_path, method: delete,do |f|
  =link_to "ログアウト", destroy_user_session_path, method: :delete, class: "log-out-box__button"
= render "shared/red-camera"

app/views/shared/_new-login-credit.haml
.credit-body.login-hidden
  .credit-body__container-2
    .credit-body__container-2__header
      %h1.credit-body__container-2__header__h1 
        = image_tag "main-logo.png" , width: 240, height:70
      .progress-bar-contents
        .progress-bar
          .progress-bar__text
            会員登録
          .progress-bar__dot.dot-bars1.red-dot
            ●
            .progress-bar__dot__bars.dot-bar1#red-bar
        .progress-bar
          .progress-bar__text
            電話番号認証
          .progress-bar__dot.dot-bars2.red-dot
            ●
            .progress-bar__dot__bars.dot-bars2#red-bar
        .progress-bar
          .progress-bar__text
            お届け先住所入力
          .progress-bar__dot.dot-bar3.red-dot
            ●
            .progress-bar__dot__bars.dot-bars3#red-bar
        .progress-bar
          .progress-bar__text.login-input-credit
            支払い方法
          .progress-bar__dot.dot-bar4.red-dot
            ●
            .progress-bar__dot__bars.dot-bars4
        .progress-bar
          .progress-bar__text
            完了
          .progress-bar__dot.dot-bars5
            ●
    .credit-card-resistration-2
      .credit-card-resistration__title
        支払い方法
      .credit-card-resistration__box
        .card-information-box
          .card-information-box__card-number
            .label-require-icon
              %label.card-information-box__label
                カード番号
              .card-information-box__require-icon2
                必須
            %input.card-information-box__input{placeholder: "半角数字のみ"}
            = image_tag("creditcards.png", class:"card-information-box__picture")
          .card-information-box__expiration
            .label-require-icon
              %label.card-information-box__label
                有効期限
              .card-information-box__require-icon2
                必須
            %select.card-information-box__select 
            %span.card-information-box__select__text
              月
            %select.card-information-box__select.card-information-box__select2
            %span.card-information-box__select__text
              年
          .card-information-box__security
            .label-require-icon
              %label.card-information-box__label
                セキュリティコード
              .card-information-box__require-icon2
                必須
            %input.card-information-box__input{placeholder: "カード背面4桁もしくは3桁の番号"}
          %button.card-information-box__submit
            次へ進む
    = render "shared/footer-log"

app/views/shared/_profile_form.haml
= render "shared/red-camera"
.profile-edit
  .profile-edit__title
    プロフィール
  .profile-edit__top-box
    .profile-edit__top-box__container
      = image_tag "avator.png", class:"profile-edit__top-box__avator"
      %input.profile-edit__top-box__name{placeholder: "#{current_user.nickname}"}
  .profile-edit__under-box
    .profile-edit__under-box__input
      =  text_area :profile, :profile, class: "profile-edit__under-box__input__form",placeholder: "current_user.profile（空であれば定型文を記述してください）" 
    = link_to "変更する", "" ,{class: "profile-edit__under-box__submit"}

app/views/shared/_progressive_bar.haml
.progress-bar-box
  .progress-bar
    .progress-bar__title
      会員登録
    .progress-bar__dot.dot-bar1
      ●
      .progress-bar__dot__bar.dot-bar1
  .progress-bar
    .progress-bar__title
      電話番号認証
    .progress-bar__dot.dot-bar2
      ●
      .progress-bar__dot__bar.dot-bar2
  .progress-bar
    .progress-bar__title
      お届け先住所入力
    .progress-bar__dot.dot-bar3
      ●
      .progress-bar__dot__bar.dot-bar3
  .progress-bar
    .progress-bar__title
      支払い方法
    .progress-bar__dot.dot-bar4
      ●
      .progress-bar__dot__bar.dot-bar4
  .progress-bar
    .progress-bar__title
      完了
    .progress-bar__dot.dot-bar5
      ●

app/views/shared/_red-camera.haml
= link_to new_sell_path, class: "red-camera" do
  .footer-sell-btn
    .footer-sell-btn__camera
      出品
      = fa_icon 'camera', class: "fa-3x footer-sell-btn__link__camera" 

app/views/shared/_search-item.haml
-# localオプションで変数をitemに渡してください
-# 使用例です。
-#  = render 'shared/search-item' ,item: @test

-# sold-flagは売約済みか否かを示す部分です。

.itemsearch-box
  - if item.buyer_id != nil
    .sold-flag  
    .sold-flag__text
      sold 
  = link_to item_path(item.id) ,class: "itemsearch-box__link" do
    - begin
      = image_tag "#{item.images.first.url}",class:"itemsearch-box__picture" 
    - rescue  
      = image_tag "",class:"itemsearch-box__picture" 
    .itemsearch-box__discription
      = item.name
      .itemsearch-box__discription__info
        .itemsearch-box__discription__price
          ¥
          - price = add_comma(item.price)
          = price
        .itemsearch-box__discription__like
          = fa_icon 'heart-o', class:'heart'

app/views/shared/_side-list.haml
.side-list
  %nav.mypage-nav
    %ul.mypage-nav__list
      %li.side-bar__link-box
        = link_to mypage_path, class: "side-links" do
          マイページ
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          お知らせ
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          やることリスト
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          いいね！一覧
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to new_sell_path, class: "side-links" do
          出品する
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to mypage_listings_path, class: "side-links" do
          出品した商品 - 出品中
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          出品した商品 - 取引中
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          出品した商品 - 売却済
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          購入した商品 - 過去の取引
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          ニュース一覧
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          評価一覧
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          マイページ
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          お問い合わせ
          %i.fa.fa-angle-right

    %h3.mypage-nav__head
      メルペイ
    %ul.mypage-nav__list
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          売り上げ・振り込み申請
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          ポイント
          %i.fa.fa-angle-right
        
    %h3.mypage-nav__head
      設定
    %ul.mypage-nav__list
      %li.side-bar__link-box
        = link_to mypage_profile_path, class: "side-links" do
          プロフィール
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          発送元・お届け先住所変更
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to mypage_cards_path, class: "side-links" do
          お支払情報変更
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          メール/パスワード
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          本人確認
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          電話番号の確認
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to mypage_logout_path, class: "side-links" do
          ログアウト
          %i.fa.fa-angle-right

app/views/shared/_toppage-itembox.haml
//render pageにpertialで実装する
- @items.each do |item|
  .item-box-contents__items-box 
    = link_to item_path(item.id), class: "item-box-contents__items-box__name" do
      .item-box-contents__items-box__photo.toppage-item-card
        - if item.buyer_id != nil
          .sold-flag  
          .sold-flag__text
            sold 
        - begin
          = image_tag "#{item.images.first.url}",class:"toppage-item-pic" 
        - rescue  
          = image_tag "",class:"itemsearch-box__picture" 
      .item-box-contents__items-box__body
        .item-box-contents__items-box__body__name
          = item.name
        .item-box-contents__items-box__body__number
          .items-box-price
            - price =  add_comma(item.price)
            = "￥" + price
          .items-box-heart
          -#  いいね機能を実装する場合は以下を外してください。
            -# .items-box-heart__icon
            -#   = fa_icon 'heart', class: "search-icon-right"
            -# .items-box-heart__count
            -#   2