config/routes.rb
Rails.application.routes.draw do
  get 'purchase/index'
  get 'purchase/done'
  get 'card/new'
  get 'card/show'
  devise_for :users
  root 'test#index'
  resources :search,only: [:index]
  resources :category,only:[:index,:show,:new]
  resource :mypage do
    resource :profile ,only: [:show]
    resource :cards ,only: [:new, :show, :create] do
      collection do
        post 'pay', to: 'cards#pay'
        post 'delete', to: 'cards#delete'
        get 'credit_add', to: 'cards#credit_add'
      end
    end
    resource :logout ,only: [:show]
    resource :listings ,only:[:show] do
      resources :display, only:[:show,:destroy]
    end
  end
  resources :items, only: [:show,:destroy]


  resources :sells,only:[:index,:new,:create,:edit,:update]

  resource :users,only: [:new]
  
  resources :signup do
    collection do
      get 'new_login'
      get 'login_menber_information'
      get 'login_phone_number'
      get 'new_login_adress' # ここで、入力の全てが終了する
      get 'new_login_complete' # 登録完了後のページ
    end
  end

  resources :purchase, only: [:index, :show] do
    collection do
      # get 'show', to: 'purchase#show'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end
end

app/controllers/purchase_controller.rb
class PurchaseController < ApplicationController

  require 'payjp'

  def show
    @item = Item.find(params[:id])
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to controller: "cards", action: "show"
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  def pay
    item = Item.find(params[:item_id])
    price = item.price
    card = Card.where(user_id: current_user.id).first
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    Payjp::Charge.create(
    amount: price,
    customer: card.customer_id,
    currency: 'jpy',
  )
  item.update(buyer_id:"1")
  redirect_to action: 'done' 
  end

  def done
  end
end

app/views/purchase/done.html.haml
.purchase
  .purchase__image
    = image_tag "main-logo.png" , width: 240, height:70
  .purchase__container
    .purchase__container__title
      購入が完了しました！
    .purchase__container__description
      購入完了しました。出品者の連絡をお待ちください！
      %br
      またのご利用お待ちしております。
    = link_to "トップページへ戻る", root_path, class: "purchase__container__link"
  .purchase__container__footer
  = render "shared/footer-log"

app/views/purchase/show.html.haml
= form_with url: pay_purchase_index_path, action: :pay, method: :post, local: true do |f|
  .log-body
    .log-body__container
      = render "shared/header-log"
      .buy-item-wrapper
        .body-confirmation
          %h2.body-confirmation__title
            購入内容の確認
          .body-confirmation__main
            .body-confirmation__main__inner
              .body-confirmation__main__inner__top
                %h3.buy-item-image
                  = image_tag "#{@item.images.first.url}", width: 64, height:64
                %p.buy-item-name
                  = @item.name
              .body-confirmation__main__inner__bottom
                %p.buy-price
                  = "¥#{@item.price.to_s(:delimited)}"
                  %span.buy-price__shipping-fee
                    送料込み
                %ul.buy-point
                  ポイントはありません
                %ul.final-price
                  %li.final-price__cell
                    支払い金額
                  %li.final-price__cell2
                    = "¥#{@item.price.to_s(:delimited)}"
                %input{name: "item_id", type: "hidden", value: @item.id}
                = f.submit "購入する", class: "submit-buy-button"    
          .body-confirmation__address
            .body-confirmation__address__inner
              %h3.body-confirmation__address__inner__ship
                配送先
              .body-confirmation__address__inner__box
              = "〒#{current_user.post_number}"
              %br
                = "#{Prefecture.find(current_user.prefecture).name}" + "#{current_user.city}" + "#{current_user.address}" + "#{current_user.building_name}" 
              %br
              = "#{current_user.first_name}" + "#{current_user.family_name}"
              %br
              .body-confirmation__address__inner__bottom
                =link_to "変更する ＞","",class: "body-confirmation__address__inner__bottom__link"
          .body-confirmation__how-to-pay
            .body-confirmation__how-to-pay__inner
              %h4.body-confirmation__how-to-pay__inner__cregit
                支払い方法
              .body-confirmation__how-to-pay__inner__box
                = "**** **** **** " + @default_card_information.last4
                %br
                - exp_month = @default_card_information.exp_month.to_s
                - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                = exp_month + " / " + exp_year
                %br
                .body-confirmation__how-to-pay__inner__cregit__pic
                  = image_tag "jcb.png",size: "25x25"
                .body-confirmation__address__inner__bottom
                  =link_to "変更する ＞","",class: "body-confirmation__address__inner__bottom__link"
      = render "shared/footer-log"